# flake8: noqa

"""
    https://api.partner.microsoft.com/v1.0/ingestion

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "v1"

# import ApiClient
from .api_client import ApiClient

# import Configuration
from .configuration import Configuration

# import exceptions
from .exceptions import OpenApiException
from .exceptions import ApiAttributeError
from .exceptions import ApiTypeError
from .exceptions import ApiValueError
from .exceptions import ApiKeyError
from .exceptions import ApiException
