# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.1, generator: @autorest/python@6.1.6)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Optional, TYPE_CHECKING

from azure.core import PipelineClient
from azure.core.rest import HttpRequest, HttpResponse

from ._configuration import HttpsApiPartnerMicrosoftComV10IngestionConfiguration
from ._operations import HttpsApiPartnerMicrosoftComV10IngestionOperationsMixin
from ._serialization import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Dict


class HttpsApiPartnerMicrosoftComV10Ingestion(
    HttpsApiPartnerMicrosoftComV10IngestionOperationsMixin
):  # pylint: disable=client-accepts-api-version-keyword
    """HttpsApiPartnerMicrosoftComV10Ingestion.

    :param authorization: User authorization. Required.
    :type authorization: str
    :param product_id: ID of product. Required.
    :type product_id: str
    :param instance_id: Resource instance ID. Required.
    :type instance_id: str
    :param submission_id: ID of submission. Required.
    :type submission_id: str
    :param variant_id: ID of variant. Required.
    :type variant_id: str
    :param listing_id: ID of listing. Required.
    :type listing_id: str
    :param asset_id: ID of asset. Required.
    :type asset_id: str
    :param image_id: ID of image. Required.
    :type image_id: str
    :param feature_availability_id: Feature availability ID. Required.
    :type feature_availability_id: str
    :param client_request_id: ID of request provIDed by user. Default value is None.
    :type client_request_id: str
    :param expand: Use $expand to include MarketStates, PriceSchedules, and Trial in
     request/response. Default value is None.
    :type expand: str
    :keyword endpoint: Service URL. Default value is
     "https://api.partner.microsoft.com/v1.0/ingestion".
    :paramtype endpoint: str
    """

    def __init__(  # pylint: disable=missing-client-constructor-parameter-credential
        self,
        authorization: str,
        product_id: str,
        instance_id: str,
        submission_id: str,
        variant_id: str,
        listing_id: str,
        asset_id: str,
        image_id: str,
        feature_availability_id: str,
        client_request_id: Optional[str] = None,
        expand: Optional[str] = None,
        *,
        endpoint: str = "https://api.partner.microsoft.com/v1.0/ingestion",
        **kwargs: Any
    ) -> None:
        self._config = HttpsApiPartnerMicrosoftComV10IngestionConfiguration(
            authorization=authorization,
            product_id=product_id,
            instance_id=instance_id,
            submission_id=submission_id,
            variant_id=variant_id,
            listing_id=listing_id,
            asset_id=asset_id,
            image_id=image_id,
            feature_availability_id=feature_availability_id,
            client_request_id=client_request_id,
            expand=expand,
            **kwargs
        )
        self._client = PipelineClient(base_url=endpoint, config=self._config, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False

    def send_request(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client.send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> HttpsApiPartnerMicrosoftComV10Ingestion
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
